FROM node:20-slim AS builder
WORKDIR /app

COPY package*.json ./
RUN npm install --production=false

COPY . .

ARG VITE_TRANSACTIONS_BASE_URL
ENV VITE_TRANSACTIONS_BASE_URL=${VITE_TRANSACTIONS_BASE_URL}

ARG VITE_PAYMENT_BASE_URL
ENV VITE_PAYMENT_BASE_URL=${VITE_PAYMENT_BASE_URL}

ARG VITE_IAM_BASE_URL
ENV VITE_IAM_BASE_URL=${VITE_IAM_BASE_URL}

ARG VITE_BASE_PATH="/"
ENV VITE_BASE_PATH=${VITE_BASE_PATH}

RUN npm run build

# Structure output based on base path
RUN mkdir -p /app/public_html && \
    if [ "$VITE_BASE_PATH" = "/transactions/" ]; then \
      mkdir -p /app/public_html/transactions && \
      cp -r /app/dist/* /app/public_html/transactions/; \
    else \
      cp -r /app/dist/* /app/public_html/; \
    fi

FROM nginx:alpine AS runner
COPY --from=builder /app/public_html /usr/share/nginx/html

# Minimal nginx config to serve single-page app
RUN rm /etc/nginx/conf.d/default.conf
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["/usr/sbin/nginx", "-g", "daemon off;"]
