FROM node:20-slim AS builder
WORKDIR /app

COPY package*.json ./
RUN npm install --production=false

COPY . .

ARG VITE_TRANSACTIONS_BASE_URL
ENV VITE_TRANSACTIONS_BASE_URL=${VITE_TRANSACTIONS_BASE_URL}

ARG VITE_PAYMENT_BASE_URL
ENV VITE_PAYMENT_BASE_URL=${VITE_PAYMENT_BASE_URL}

ARG VITE_IAM_BASE_URL
ENV VITE_IAM_BASE_URL=${VITE_IAM_BASE_URL}

RUN npm run build

FROM nginx:alpine AS runner
COPY --from=builder /app/dist /usr/share/nginx/html

# Minimal nginx config to serve single-page app
RUN rm /etc/nginx/conf.d/default.conf
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["/usr/sbin/nginx", "-g", "daemon off;"]
