version: '3.8'

services:
  vault:
    image: hashicorp/vault:1.17
    container_name: vault
    entrypoint: ["vault"]
    command: ["server", "-config=/vault/config/vault.hcl"]
    cap_add:
      - IPC_LOCK
    environment:
      SKIP_CHOWN: "true"
      SKIP_SETCAP: "true"
    ports:
      - "8200:8200"
    volumes:
      - ./vault/config:/vault/config:ro
      - ./.vault/data:/vault/data
    networks:
      - vault-network
      - egs-network

networks:
  vault-network:
    name: vault-network
  egs-network:
    external: true
