server:
  port: 8081

spring:
  application:
    name: transaction-service
  
  datasource:
    url: jdbc:postgresql://localhost:5432/transaction_db
    username: myuser
    password: mypassword
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

blockchain:
  node:
    url: "https://polygon-amoy.infura.io/v3/af4602fc6da24f91bb25a7b9e55a2ec4"
    chainId: 80002
  contract:
    address: "0x0000000000000000000000000000000000000000"
    decimals: 18

# Keycloak / OIDC settings used for Composer login flow
keycloak:
  url: "http://localhost:8080"
  realm: "microservices"
  client-id: "iam-service"
  client-secret: "4g70qaoXmfnaIf7d9LgSRtnJCjIBBcha"

# Application settings
app:
  dev-mode: true  # DEV MODE: Simula blockchain sem conectar realmente. DESATIVAR em produção!
  bank-wallet: "0x86a9906e6bd2ef137d6d5339154611de7a41b178"
  payment-service-url: "http://localhost:5002"
