FROM node:20-slim AS builder
WORKDIR /app

COPY package*.json ./
RUN npm install --production=false

COPY . .

ARG VITE_PROXY_TARGET
ENV VITE_PROXY_TARGET=${VITE_PROXY_TARGET}
ARG VITE_API_BASE_URL
ENV VITE_API_BASE_URL=${VITE_API_BASE_URL}
ARG VITE_PAYMENT_DEFAULT_REDIRECT_URL
ENV VITE_PAYMENT_DEFAULT_REDIRECT_URL=${VITE_PAYMENT_DEFAULT_REDIRECT_URL}
ARG VITE_STRIPE_PUBLISHABLE_KEY
ENV VITE_STRIPE_PUBLISHABLE_KEY=${VITE_STRIPE_PUBLISHABLE_KEY}

RUN npm run build

FROM nginx:alpine AS runner
COPY --from=builder /app/dist /usr/share/nginx/html

RUN rm /etc/nginx/conf.d/default.conf
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["/usr/sbin/nginx", "-g", "daemon off;"]
